// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.865
package counterapptemplates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "fmt"

func Counter(value int, maxValue int) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div id=\"counter-container\" class=\"card card-bordered bg-base-100 shadow-xl w-full max-w-md mx-auto\"><div class=\"card-body items-center text-center\"><!-- Counter buttons first --><div class=\"flex items-center gap-4 text-2xl font-bold mb-8\"><button hx-post=\"/decrement\" hx-target=\"#counter-container\" hx-swap=\"outerHTML\" class=\"btn btn-primary flex items-center gap-2\"><svg xmlns=\"http://www.w3.org/2000/svg\" class=\"h-5 w-5\" viewBox=\"0 0 20 20\" fill=\"currentColor\"><path fill-rule=\"evenodd\" d=\"M3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z\" clip-rule=\"evenodd\"></path></svg> Decrement</button><div class=\"text-3xl min-w-16 h-16 flex items-center justify-center bg-base-200 rounded-full\"><span id=\"counter\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprint(value))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `counterapp/templates/counter.templ`, Line: 23, Col: 46}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</span></div><button hx-post=\"/increment\" hx-target=\"#counter-container\" hx-swap=\"outerHTML\" class=\"btn btn-secondary flex items-center gap-2\"><svg xmlns=\"http://www.w3.org/2000/svg\" class=\"h-5 w-5\" viewBox=\"0 0 20 20\" fill=\"currentColor\"><path fill-rule=\"evenodd\" d=\"M10 3a1 1 0 011 1v5h5a1 1 0 110 2h-5v5a1 1 0 11-2 0v-5H4a1 1 0 110-2h5V4a1 1 0 011-1z\" clip-rule=\"evenodd\"></path></svg> Increment</button></div><!-- Max value display --><div class=\"mb-6 text-center\"><p class=\"text-base-content mb-2\">Current Max Value: <span class=\"badge badge-secondary badge-lg\" id=\"current-max\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprint(maxValue))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `counterapp/templates/counter.templ`, Line: 41, Col: 143}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</span></p></div><!-- Form with local AlpineJS validation --><div class=\"w-full\" x-data=\"{ maxCount: &#39;&#39;, error: &#39;&#39; }\"><form class=\"flex flex-col gap-2\" hx-post=\"/set-max\" hx-target=\"#counter-container\" hx-swap=\"outerHTML\"><div class=\"join w-full\"><input type=\"number\" name=\"max\" min=\"1\" max=\"100\" placeholder=\"Enter max value (1-100)\" class=\"input input-bordered input-secondary join-item flex-grow\" required x-model.number=\"maxCount\" @input=\"error = (maxCount &lt; 1 || maxCount &gt; 100) ? &#39;Value must be between 1 and 100&#39; : &#39;&#39;\"> <button type=\"submit\" class=\"btn btn-secondary join-item\" :disabled=\"error !== &#39;&#39;\" :class=\"{ &#39;btn-disabled&#39;: error !== &#39;&#39; }\"><svg xmlns=\"http://www.w3.org/2000/svg\" class=\"h-5 w-5 mr-1\" viewBox=\"0 0 20 20\" fill=\"currentColor\"><path fill-rule=\"evenodd\" d=\"M10 18a8 8 0 100-16 8 8 0 000 16zm1-11a1 1 0 10-2 0v2H7a1 1 0 100 2h2v2a1 1 0 102 0v-2h2a1 1 0 100-2h-2V7z\" clip-rule=\"evenodd\"></path></svg> Max Count</button></div><!-- Error message display --><div x-show=\"error !== &#39;&#39;\" x-text=\"error\" class=\"text-error text-sm mt-1\"></div></form></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
